// family_service.dart — Family group management and live location sharing.
//
// PRIVACY ARCHITECTURE:
//   All location data flows: device → Supabase (TLS) → family members only.
//   The family_locations table has RLS policies that restrict SELECT to
//   members of the same group_id. No location ever leaves Supabase to any
//   third party. Rows expire after 10 minutes via expires_at column.
//
// INVITE CODE:
//   6-character alphanumeric code (e.g. "BRV42X"). The creator shares this
//   out-of-band (text, verbal). The code is never sent as a push notification
//   or stored in any log. Codes can be regenerated by the group creator.

import 'dart:async';
import 'dart:math';

import 'package:latlong2/latlong.dart';

import '../models/family_model.dart';
import 'supabase_service.dart';

class FamilyService {
  FamilyService._();
  static final FamilyService instance = FamilyService._();

  static const int _locationTtlMinutes = 10;
  static const int _maxGroupSize = 10;

  // =========================================================================
  // Group management
  // =========================================================================

  /// Creates a new family group owned by the current user.
  Future<FamilyGroup> createGroup(String name) async {
    final String userId = _requireUserId();
    final String code = _generateInviteCode();

    final Map<String, dynamic> row =
        await SupabaseService.client.from('family_groups').insert(<String, dynamic>{
      'name': name,
      'invite_code': code,
      'created_by': userId,
    }).select().single();

    final FamilyGroup group = FamilyGroup.fromJson(row);

    // Auto-join as first member.
    await _joinGroup(group.id, userId);
    return group;
  }

  /// Joins an existing group by 6-character invite code.
  /// Returns the group, or throws [FamilyServiceException] on failure.
  Future<FamilyGroup> joinByCode(String code) async {
    final String userId = _requireUserId();
    final String normalised = code.trim().toUpperCase();

    // Fetch the group matching this code.
    final List<Map<String, dynamic>> rows = await SupabaseService.client
        .from('family_groups')
        .select()
        .eq('invite_code', normalised)
        .limit(1);

    if (rows.isEmpty) {
      throw const FamilyServiceException('Invite code not found.');
    }

    final FamilyGroup group = FamilyGroup.fromJson(rows.first);

    // Check membership count.
    final List<Map<String, dynamic>> members = await SupabaseService.client
        .from('family_memberships')
        .select('user_id')
        .eq('group_id', group.id);

    if (members.length >= _maxGroupSize) {
      throw const FamilyServiceException('This group is full (10 members max).');
    }

    // Already a member?
    final bool alreadyMember = members.any(
      (Map<String, dynamic> m) => m['user_id'] == userId,
    );
    if (!alreadyMember) {
      await _joinGroup(group.id, userId);
    }

    return group;
  }

  /// Leaves the user's current group. If the user is the last member,
  /// the group is deleted.
  Future<void> leaveGroup(String groupId) async {
    final String userId = _requireUserId();

    await SupabaseService.client
        .from('family_memberships')
        .delete()
        .eq('group_id', groupId)
        .eq('user_id', userId);

    // Delete location ping if it exists.
    await SupabaseService.client
        .from('family_locations')
        .delete()
        .eq('group_id', groupId)
        .eq('user_id', userId);

    // Clean up orphaned group.
    final List<Map<String, dynamic>> remaining = await SupabaseService.client
        .from('family_memberships')
        .select('user_id')
        .eq('group_id', groupId);

    if (remaining.isEmpty) {
      await SupabaseService.client
          .from('family_groups')
          .delete()
          .eq('id', groupId);
    }
  }

  /// Regenerates the invite code for a group (creator only).
  Future<String> regenerateInviteCode(String groupId) async {
    final String userId = _requireUserId();
    final String newCode = _generateInviteCode();

    await SupabaseService.client
        .from('family_groups')
        .update(<String, dynamic>{'invite_code': newCode})
        .eq('id', groupId)
        .eq('created_by', userId); // RLS + app-level creator check

    return newCode;
  }

  // =========================================================================
  // Member queries
  // =========================================================================

  /// Loads the group the current user belongs to, if any.
  Future<FamilyGroup?> loadMyGroup() async {
    final String userId = _requireUserId();

    // Find their membership row.
    final List<Map<String, dynamic>> memberRows = await SupabaseService.client
        .from('family_memberships')
        .select('group_id')
        .eq('user_id', userId)
        .limit(1);

    if (memberRows.isEmpty) return null;

    final String groupId = memberRows.first['group_id'] as String;

    final Map<String, dynamic> groupRow = await SupabaseService.client
        .from('family_groups')
        .select()
        .eq('id', groupId)
        .single();

    return FamilyGroup.fromJson(groupRow);
  }

  /// Loads all members of [groupId] with their display names and archetypes.
  Future<List<FamilyMember>> loadMembers(String groupId) async {
    // Join family_memberships → users → archetype_profiles
    final List<Map<String, dynamic>> rows = await SupabaseService.client
        .from('family_memberships')
        .select('''
          user_id,
          group_id,
          joined_at,
          users:user_id (
            display_name,
            location_sharing_enabled
          ),
          archetype_profiles:user_id (
            current_archetype
          )
        ''')
        .eq('group_id', groupId);

    return rows.map((Map<String, dynamic> row) {
      final Map<String, dynamic> user =
          row['users'] as Map<String, dynamic>? ?? <String, dynamic>{};
      final Map<String, dynamic> archData =
          row['archetype_profiles'] as Map<String, dynamic>? ?? <String, dynamic>{};
      return FamilyMember(
        userId: row['user_id'] as String,
        displayName: user['display_name'] as String? ?? 'Member',
        groupId: row['group_id'] as String,
        joinedAt: DateTime.parse(row['joined_at'] as String),
        isSharingLocation: user['location_sharing_enabled'] as bool? ?? false,
        archetype: archData['current_archetype'] as String?,
      );
    }).toList();
  }

  // =========================================================================
  // Live location
  // =========================================================================

  /// Publishes the user's current GPS position to the family group.
  /// Only called when location_sharing_enabled = true.
  /// The row expires after [_locationTtlMinutes] minutes.
  Future<void> publishLocation({
    required String groupId,
    required LatLng position,
    required double speedMps,
  }) async {
    final String userId = _requireUserId();
    final DateTime now = DateTime.now().toUtc();
    final DateTime expires =
        now.add(Duration(minutes: _locationTtlMinutes));

    await SupabaseService.client.from('family_locations').upsert(
      <String, dynamic>{
        'user_id': userId,
        'group_id': groupId,
        'latitude': position.latitude,
        'longitude': position.longitude,
        'speed_mps': speedMps,
        'updated_at': now.toIso8601String(),
        'expires_at': expires.toIso8601String(),
      },
      onConflict: 'user_id,group_id',
    );
  }

  /// Returns a real-time stream of all non-expired family member locations
  /// in [groupId], excluding the current user's own row.
  Stream<List<FamilyLocation>> streamFamilyLocations(String groupId) {
    final String userId = _requireUserId();

    return SupabaseService.client
        .from('family_locations')
        .stream(primaryKey: <String>['user_id', 'group_id'])
        .eq('group_id', groupId)
        .map((List<Map<String, dynamic>> rows) {
          final DateTime now = DateTime.now();
          return rows
              .where((Map<String, dynamic> r) =>
                  r['user_id'] != userId &&
                  DateTime.parse(r['expires_at'] as String).isAfter(now))
              .map(FamilyLocation.fromJson)
              .toList();
        });
  }

  // =========================================================================
  // Private helpers
  // =========================================================================

  Future<void> _joinGroup(String groupId, String userId) async {
    await SupabaseService.client.from('family_memberships').upsert(
      <String, dynamic>{
        'group_id': groupId,
        'user_id': userId,
        'joined_at': DateTime.now().toUtc().toIso8601String(),
      },
      onConflict: 'group_id,user_id',
    );
  }

  String _generateInviteCode() {
    const String chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; // no 0/O/1/I
    final Random rng = Random.secure();
    return List<String>.generate(6, (_) => chars[rng.nextInt(chars.length)])
        .join();
  }

  String _requireUserId() {
    final String? uid =
        SupabaseService.client.auth.currentSession?.user.id;
    if (uid == null) throw const FamilyServiceException('Not authenticated.');
    return uid;
  }
}

class FamilyServiceException implements Exception {
  const FamilyServiceException(this.message);
  final String message;
  @override
  String toString() => 'FamilyServiceException: $message';
}
